version: "3"
services:
  api-java:
    image: leandrobhmg/api-person:0.0.12
    ports:
      - "8080:8080"
    networks:
      - person-network

  api-node:
    image: leandrobhmg/api-node_mock:0.0.12
    ports:
      - "3000:3000"
    networks:
      - person-network

networks:
  person-network:
