@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

SHOW_PERSON_OUTLINE()

title Container Diagram for api person

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Container Diagram for api person

Person(user, "User", "User")

System_Boundary(Leandro, "Leandro") {

    Container(api_person, "api-person", "GraphQL API", "Java Service", "Java", $sprite="java")
    ContainerDb(db_person, "Database", "files json Database", "Data", $sprite="mysql")
    Container(person_service, "Person Service", "Node.js Service", "Node.js App")
    Container(address_service, "Address Service", "Node.js Service", "Node.js App")
    Container(document_service, "Document Service", "Node.js Service", "Node.js App")
    Container(phone_service, "Phone Service", "Node.js Service", "Node.js App")

    Rel(user, api_person, "Uses", "Uses")

    Rel(api_person, person_service, "Sends Requests to", "HTTP")
    Rel(api_person, address_service, "Sends Requests to", "HTTP")
    Rel(api_person, document_service, "Sends Requests to", "HTTP")
    Rel(api_person, phone_service, "Sends Requests to", "HTTP")

    Rel(person_service, db_person, "Reads/Writes", "Reads/Writes")
    Rel(address_service, db_person, "Reads/Writes", "Reads/Writes")
    Rel(document_service, db_person, "Reads/Writes", "Reads/Writes")
    Rel(phone_service, db_person, "Reads/Writes", "Reads/Writes")
}

@enduml