spring:
  application:
    name: api-person
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

graphql:
  servlet:
    enabled: true
    exception-handlers-enabled: true
  extended-scalars: Date
  playground:
    settings:
      schema.polling.enable: false
    enabled: true
    headers:
      Authorization: Bearer ${token}
    tabs:
      - name: Get People
        query: classpath:playground/people.graphql
        variables: classpath:playground/people_input.json
#  voyager:
#    enabled: true
#    basePath: /
#    mapping: /voyager
#    endpoint: /graphql
#    cdn:
#      enabled: false
#      version: latest
#    pageTitle: Voyager
#    displayOptions:
#      skipRelay: true
#      skipDeprecated: true
#      rootType: Query
#      sortByAlphabet: false
#      showLeafFields: true
#      hideRoot: false
#    hideDocs: false
#    hideSettings: false

api:
  node:
    base-url: http://127.0.0.1:3000/

