name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badges for Module Application
        id: jacocoMod1
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: application/target/site/jacoco/jacoco.csv
          coverage-badge-filename: application-coverage-badge.svg
          branches-badge-filename: application-branches-badge.svg
          coverage-label: coverage (application)
          branches-label: branches (application)

      - name: Generate JaCoCo Badges for Module Repository
        id: jacocoMod2
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: repository/target/site/jacoco/jacoco.csv
          coverage-badge-filename: repository-coverage-badge.svg
          branches-badge-filename: repository-branches-badge.svg
          coverage-label: coverage (repository)
          branches-label: branches (repository)

      - name: Generate JaCoCo Badge
        id: jacocoMod3
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: application/target/site/jacoco/jacoco.csv
          badges-directory: .github/badges
          generate-coverage-badge: true
          coverage-badge-filename: jacoco.svg
          generate-branches-badge: false
          branches-badge-filename: branches.svg
          generate-coverage-endpoint: false
          coverage-endpoint-filename: jacoco.json
          generate-branches-endpoint: false
          branches-endpoint-filename: branches.json
          generate-summary: false
          summary-filename: coverage-summary.json
          coverage-label: coverage
          branches-label: branches
          colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
          intervals: 100 90 80 70 60 0
          on-missing-report: fail
          fail-if-coverage-less-than: 0
          fail-if-branches-less-than: 0
          fail-on-coverage-decrease: false
          fail-on-branches-decrease: false

      - name: Commit the badge (if it changed)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://github.com/${{ github.repository }}
          git add .
          git commit -m ":rocket: adding generated badges" || exit 0
          git push
