name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badges for Module Application
        id: jacocoMod1
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: application/target/site/jacoco/jacoco.csv
          coverage-badge-filename: application-coverage-badge.svg
          branches-badge-filename: application-branches-badge.svg
          coverage-label: coverage (module application)
          branches-label: branches (module application)

      - name: Generate JaCoCo Badges for Module Repository
        id: jacocoMod2
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: repository/target/site/jacoco/jacoco.csv
          coverage-badge-filename: repository-coverage-badge.svg
          branches-badge-filename: repository-branches-badge.svg
          coverage-label: coverage (module repository)
          branches-label: branches (module repository)
      - name: Commit the badge (if it changed)
        permissions:
          contents: write
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://github.com/${{ github.repository }}
          git add .
          git commit -m ":rocket: adding generated badges" || exit 0
          git push
